config/routes.rb
RottenMangoes::Application.routes.draw do

  namespace :admin do
    resources :users
    resources :movies
  end

  resources :movies, only: [:show, :index] do
    collection do
      get 'search'
      get 'highest_rated'
      get 'new_releases'
    end
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show] do
    resources :reviews, only: [:index]
  end

  resource :session, only: [:new, :create, :destroy, :update]

  root to: 'movies#index'
 

  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews

  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: { only_integer: true }
  validates :description, presence: true
  validates :poster, presence: true
  validates :release_date, presence: true

  mount_uploader :poster, PosterUploader

  scope :query, ->(query) { where("lower(title || director) LIKE ?", "%#{query}%") }
  scope :short, -> { where("runtime_in_minutes < 90") }
  scope :medium, -> { where("runtime_in_minutes BETWEEN 90 AND 120") }
  scope :long, -> { where("runtime_in_minutes > 120") }
  scope :highest_rated, -> { joins(:reviews).order("AVG(reviews.rating_out_of_ten) DESC").group("movies.id").having("AVG(reviews.rating_out_of_ten) > 5") }

  def review_average
    if reviews.size == 0
      return 0
    else
      reviews.sum(:rating_out_of_ten)/reviews.size
    end
  end

  protected

  # def release_date_is_in_the_future
  #   if release_date.present?
  #     errors.add(:release_date, "should probably be in the future") if release_date < Date.today
  #   end
  # end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_secure_password
  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

  def role
    if self.admin
      "Admin"
    else
      "User"
    end
  end

end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster, :description
    )
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_filter :restrict_admin_access

  def index
    @users = User.page(1).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "User #{@user.full_name} created!"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def restrict_admin_access
    unless admin?
      flash[:alert] = "You are not an administrator."
      redirect_to root_path
    end
  end

  def admin?
    current_user && current_user.admin
  end

  def impersonating?
    session[:previous_id]
  end

  helper_method :current_user
  helper_method :restrict_admin_access
  helper_method :admin?
  helper_method :impersonating?


end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
    # respond_to :html, :json
  end

  def search
    @movies = Movie.query(params[:query])
    case params[:duration]
    when "short"
      @movies = @movies.short
    when "medium"
      @movies = @movies.medium
    when "long"
      @movies = @movies.long
    end
    @movies
  end

  def highest_rated
    @movies = Movie.highest_rated
  end

  def show
    @movie = Movie.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

  def update
    if session[:previous_id]
      session[:user_id] = session[:previous_id]
      session[:previous_id] = nil
      redirect_to admin_users_path
    else
      session[:previous_id] = session[:user_id]
      session[:user_id] = params[:format]
      redirect_to root_path
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_submenu.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Admin Panel</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs">
      <li role="presentation" <% if view =="users" %> class="active" <% end %> ><%= link_to "User List", admin_users_path %></li>
      <li role="presentation" <% if view =="new_user" %> class="active" <% end %> ><%= link_to "New User", new_admin_user_path %></li>
      <li role="presentation" <% if view =="movies" %> class="active" <% end %> ><%= link_to "Movie List", admin_movies_path %></li>
      <li role="presentation" <% if view =="new_movie" %> class="active" <% end %> ><%= link_to "New Movie", new_admin_movie_path %></li>
    </ul>
  </div>
</div>

app/views/admin/movies/_form.html.erb
<%= form_for([:admin, @movie], html: {class: 'form-horizontal'}) do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label "title", class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field "title", class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "release_date", "Release Date", class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"> 
      <%= f.date_field "release_date", class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "director", "Director", class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field "director", class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "runtime_in_minutes", class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.number_field "runtime_in_minutes", class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "poster", class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.file_field "poster" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "description", "Description", class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field "description", class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-default"%>
    </div>
  </div>
<% end %>

app/views/admin/movies/_movie.html.erb
<tr>
  <td><%= movie.id %></td>
  <td><%= movie.title %></td>
  <td><%= movie.director %></td>
  <td><%= movie.runtime_in_minutes %></td>
  <td><%= movie.release_date %></td>
  <td><%= movie.description %></td>
  <td><%= movie.poster %></td>
  <td><%= link_to "View", movie_path(movie) %></td>
  <td><%= link_to "Edit", edit_admin_movie_path(movie) %></td>
  <td><%= link_to "Delete", admin_movie_path(movie), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/admin/movies/index.html.erb
<div class="container">
  <%= render 'admin/submenu', view:"movies" %>
  <div class="row top-buffer">
    <div class="col-sm-12">
      <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Director</th>
        <th>Runtime in minutes</th>
        <th>Release Date</th>
        <th>Description</th>
        <th>Poster</th>
      </tr>
      <%= render @movies %>
      </table>
    </div>
  </div>
</div>

app/views/admin/movies/new.html.erb
<div class="container">
  <%= render 'admin/submenu', view:"new_movie" %>
  <div class="row top-buffer">
    <div class="col-sm-8">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user], html: {class: 'form-horizontal'}) do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label "email", class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field "email", class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "firstname", "First Name", class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"> 
      <%= f.text_field "firstname", class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "lastname", "Last Name", class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field "lastname", class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "password", class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.password_field "password", class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "password_confirmation", class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.password_field "password_confirmation", class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class='col-sm-2'>
    </div>
    <div class="col-sm-10 checkbox">
      <label class="control-label"><%= f.check_box("admin", {}, "true", "false") %>Admin</label>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-default"%>
    </div>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= user.firstname %></td>
  <td><%= user.lastname %></td>
  <td><%= user.role %></td>
  <td><%= link_to "Profile", user_path(user) %></td>
  <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
  <td><%= link_to "Delete", admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <td>
    <% unless user.admin %>
    <%= link_to "Impersonate", session_path(user), method: :patch %>
    <% end %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<%= link_to "Back to users list", admin_users_path(@users) %>

<h2>Edit this user.</h2>
<div class="container">
  <%= render 'form' %>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <%= render 'admin/submenu', view:"users" %>
  <div class="row top-buffer">
    <div class="col-sm-12">
      <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Role</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
        
      <%= render @users %>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="container">
  <%= render 'admin/submenu', view:"new_user" %>
  <div class="row top-buffer">
    <div class="col-sm-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default no-bottom-buffer">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag "logo.png", alt: "Rotten Mangoes" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Movies", movies_path %></li>
        <li><a href="#">Link</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to current_user.full_name, "#" %></li>
          <li><%= link_to "Log out", session_path("current"), method: :delete %></li>
          <% if admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Admin panel", admin_users_path %></li>
          <% end %>
        <% else %>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Log In", new_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_undernavbar.html.erb
<% if impersonating? %>
  <div class="row under_navbar">
    <div class="col-sm-12">  
      <span>Impersonating <%= current_user.full_name %>. <%= link_to "Switch back to admin account", session_path(current_user), method: :patch %></span>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <%= render 'layouts/undernavbar' %>
    <% if flash.any? %>
      <div class = "row">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value) %>
        <% end %>
      </div>
    <% end %>
    <div class = "row">
      <%= yield %>
    </div>
    <div class = "row">
    </div>
  </div>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date" %>
  </div>
  <div>
    <%= f.label "director" %><br>
    <%= f.text_field "director" %>
  </div>
  <div>
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.number_field "runtime_in_minutes" %>
  </div>
  <div>
    <%= f.label "poster" %><br>
    <%= f.file_field "poster" %>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_area "description" %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="col-md-4 col-sm-6">
<div class="media item small-bottom-buffer">
  <div class="media-left media-top">
    <%= link_to image_tag(movie.poster_url(:thumb).to_s, class: "media-object"), movie_path(movie) %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= link_to movie.title, movie_path(movie) %></h4>
    <span>(<%= movie.review_average %>/10)</span>
    <p><%= formatted_date(movie.release_date) %></p>
    <p>Directed by <%= movie.director %></p>
    <p><%= movie.runtime_in_minutes %> minutes</p>
    <p><%= movie.description %></p>
  </div>
</div>
</div>

app/views/movies/_search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
    <%= form_tag search_movies_path, {method: :get, class: "form", id: "search-movies-form"} do %> 
      <div class = "form-group">
        <%= label_tag :query, "Search:", class: "control-label" %>
        <%= text_field_tag :query, nil, class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= label_tag :duration, "Duration:", class: "control-label" %>
        <%= select_tag "duration", "<option value='all' selected='selected'>Any</option><option value='short'>Under 90 minutes</option><option value='medium'>Between 90 and 120 minutes</option><option value='long'>Over 120 minutes</option>".html_safe, {class: "form-control"} %>
      </div>
        <%= submit_tag "Search", class: "btn btn-default" %> 
    <% end %>
    </div>
  </div>
</div>

app/views/movies/_search_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
    <%= form_tag search_movies_path, {method: :get, class: "form", id: "search-movies-form"} do %> 
      <div class = "form-group">
        <%= label_tag :query, "Search:", class: "control-label" %>
        <%= text_field_tag :query, nil, class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= label_tag :duration, "Duration:", class: "control-label" %>
        <%= select_tag "duration", "<option value='all' selected='selected'>Any</option><option value='short'>Under 90 minutes</option><option value='medium'>Between 90 and 120 minutes</option><option value='long'>Over 120 minutes</option>".html_safe, {class: "form-control"} %>
      </div>
        <%= submit_tag "Search", class: "btn btn-default" %> 
    <% end %>
    </div>
  </div>
</div>

app/views/movies/_submenu.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" <% if view =="index" %> class="active" <% end %> ><%= link_to "All movies", movies_path %></li>
  <li role="presentation" <% if view =="highest_rated" %> class="active" <% end %> ><%= link_to "Highest rated", highest_rated_movies_path %></li>
  <li role="presentation" <% if view =="search" %> class="active" <% end %> ><%= link_to "Search", search_movies_path %></li>
</ul>

app/views/movies/highest_rated.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Movies</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= render 'movies/submenu', view: 'highest_rated' %>
    </div>
  </div>
  <div class="row top-buffer" id="content">
    <%= render @movies %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Movies</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= render 'movies/submenu' %>
    </div>
  </div>
  <div class="row top-buffer">
    <%= render 'search' %>
  </div>
  <div class="row top-buffer" id="content">
    <%= render @movies %>
  </div>
</div>

app/views/movies/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Movies</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= render 'movies/submenu', view: 'search' %>
    </div>
  </div>
  <div class="row top-buffer">
    <%= render 'search_form' %>
  </div>
  <div class="row top-buffer" id="content">
    <%= render @movies %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1><%= @movie.title %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4">
      <%= link_to image_tag(@movie.poster_url.to_s, class:"image-responsive"), movie_path(@movie) %>
    </div>
    <div class="col-sm-8">
      <h4>(<%= @movie.review_average %>/10)</h4>
      <h4>Directed by <%= @movie.director %></h4>
      <h4><%= @movie.runtime_in_minutes %> minutes</h4>
      <h4><%= formatted_date(@movie.release_date) %></h4>
      <p><%= @movie.description %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h3>Reviews</h3>
      <% if current_user %>
        <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
      <% else %>
        <p>Please <%= link_to "log in", new_session_path %> to write a review.</p> 
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="container">
        <%= render @movie.reviews %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_review.html.erb
<% if controller_name == "users" %>

<div class="row">
  <div class="col-lg-8 col-md-10">
    <div class="media item small-bottom-buffer">
      <div class="media-left media-top">
        <%= link_to image_tag(review.movie.poster_url(:thumb).to_s, class: "media-object"), movie_path(review.movie) %>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= link_to review.movie.title, movie_path(review.movie) %></h4>
        <p><%= review.rating_out_of_ten %>/10</p>
        <p><%= review.text %></p>
      </div>
    </div>
  </div>
</div>

<% elsif controller_name == "movies" %>

<div class="row">
  <div class="col-lg-8 col-md-10">
    <div class="media item small-bottom-buffer">
      <div class="media-left media-top">
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= link_to review.user.full_name, user_path(review.user) %></h4>
        <p><%= review.rating_out_of_ten %>/10</p>
        <p><%= review.text %></p>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label "rating_out_of_ten" %><br>
    <%= f.number_field "rating_out_of_ten" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row top-buffer">
    <div class="col-sm-12">      
      <%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
        <% if @user.errors.any? %>
          <div>
            <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
        <div class="row field form-group">
          <%= f.label "email", class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field "email" %>
          </div>
        </div>
        <div class="row field form-group">
          <%= f.label "firstname", "First Name", class: 'col-sm-2 control-label' %>
          <div class="col-sm-10"> 
            <%= f.text_field "firstname" %>
          </div>
        </div>
        <div class="row field form-group">
          <%= f.label "lastname", "Last Name", class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field "lastname" %>
          </div>
        </div>
        <div class="row field form-group">
          <%= f.label "password", class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.password_field "password" %>
          </div>
        </div>
        <div class="row field form-group">
          <%= f.label "password_confirmation", class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.password_field "password_confirmation" %>
          </div>
        </div>
        <div class="row actions form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-default" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<div class="container">
  <%= render 'form' %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Sign Up</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @user.full_name %></h1>
      <p><%= @user.email %></p>
    </div>
  </div>
  <div class="row top-buffer" id="content">
    <div class="container">
      <h3>Movie reviews</h3>
      <%= render @user.reviews %>
    </div>
  </div>
</div>